name: Published

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Bundle
        run: |
          set -e -o pipefail
          cd Example
          bundle install
