name: Unpublished

on:
  release:
    types: [unpublished]

jobs:
  test:
    runs-on: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Bundle
        run: |
          ls
